### ISSUE TITLE
Relative image URLs not working

### ISSUE THREAD

**Issue by finnito** [xsleonard/sublime-MarkdownImages#2]
Kia ora!

Thanks for plugin! It is just what I was after, but I am, having trouble getting it to work with my project.
I have a Hugo site which is basically just folders of Markdown and I use a lot of images like this

```
![](../assets/10-induction-example.png) 
```

Except it is having trouble loading the image. You can find my repo over at https://gitlab.com/Finnito/Science which you are welcome to clone and try use the plugin with.

![image](https://user-images.githubusercontent.com/6530078/84729054-d8a12600-afe6-11ea-818e-64fa95510d98.png)

Thanks for your help :)

**Comment by xsleonard** [comment]
I checked, the problem is that there is no "alt text" set between the brackets `[]`.  If there is nothing between the brackets, Sublime's markdown parser will not recognize that line as image markup.  You can put whitespace in between the brackets if you don't want to set an alt text.

**Comment by finnito** [comment]
Okay, cool. Thank you! That works.

**Comment by mef51** [comment]
I get this error even with alt text. I can tell the plugin can see the file because the box disappears if I put a typo in the filename, and the dimensions of the displayed box match the image. I tried with png and jpg files. Remote images work. 

This is on windows 10, sublime text 3.2.2 build 3211
![image](https://user-images.githubusercontent.com/1703141/106542855-97f11100-64d2-11eb-86d9-06bad834d147.png)
